export enum ElectronicDocumentStatus {
  PENDING = 'PENDING',
  SUPPLIER_NOT_FOUND = 'SUPPLIER_NOT_FOUND',
  SUPPLIER_FOUND = 'SUPPLIER_FOUND',
  ACCOUNT_REQUIRED = 'ACCOUNT_REQUIRED',
  ACCOUNT_MAPPING_REQUIRED = 'ACCOUNT_MAPPING_REQUIRED',
  ACCOUNT_MAPPED = 'ACCOUNT_MAPPED',
  PURCHASE_CREATED = 'PURCHASE_CREATED',
  PURCHASE_FAILED = 'PURCHASE_FAILED',
  READY = 'READY',
  FAILED = 'FAILED',
}
