export enum ElectronicDocumentProcessingStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUPPLIER_REQUIRED = 'SUPPLIER_REQUIRED',
  ACCOUNT_REQUIRED = 'ACCOUNT_REQUIRED',
  ACCOUNT_MAPPED = 'ACCOUNT_MAPPED',
  FAILED = 'FAILED',
}
