export enum JarvisResolutionKind {
  DEBIT_NOTE = 'DEBIT_NOTE',
  CREDIT_NOTE = 'CREDIT_NOTE',
  SUPPORT_CREDIT_NOTE = 'SUPPORT_CREDIT_NOTE',
  SUPPORT_DOCUMENT = 'SUPPORT_DOCUMENT',
  ELECTRONIC_INVOICE = 'ELECTRONIC_INVOICE',
}
