import {
  SIIGO_PAYMENT_DOCUMENT_TYPE_PURCHASE,
  SIIGO_PAYMENT_DOCUMENT_TYPE_SUPPORT,
} from '../constants/siigo.constants';

const PAYMENT_DOCUMENT_TYPE_ALIASES: Record<string, string> = {
  FC: SIIGO_PAYMENT_DOCUMENT_TYPE_PURCHASE,
  PURCHASE: SIIGO_PAYMENT_DOCUMENT_TYPE_PURCHASE,
  PURCHASE_INVOICE: SIIGO_PAYMENT_DOCUMENT_TYPE_PURCHASE,
  FACTURA_COMPRA: SIIGO_PAYMENT_DOCUMENT_TYPE_PURCHASE,
  DS: SIIGO_PAYMENT_DOCUMENT_TYPE_SUPPORT,
  SUPPORT: SIIGO_PAYMENT_DOCUMENT_TYPE_SUPPORT,
  SUPPORT_DOCUMENT: SIIGO_PAYMENT_DOCUMENT_TYPE_SUPPORT,
  DOCUMENTO_SOPORTE: SIIGO_PAYMENT_DOCUMENT_TYPE_SUPPORT,
};

export function resolveSiigoPaymentDocumentType(
  documentType?: string,
): string {
  const normalized = documentType?.trim().toUpperCase() ?? '';

  if (!normalized) {
    return SIIGO_PAYMENT_DOCUMENT_TYPE_PURCHASE;
  }

  return PAYMENT_DOCUMENT_TYPE_ALIASES[normalized] ?? normalized;
}
